# Generated by Django 4.2 on 2025-10-12 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rsvp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Check-in notes', null=True)),
                ('checked_in_by', models.ForeignKey(help_text='Staff member who performed the check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('rsvp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='rsvp.rsvp')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'db_table': 'checkins',
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
